INSERT INTO CATEGORY (`NAME`,`CODE`,`STUDY_GUIDE`,`DESCRIPTION`,`STATUS`,`ORDER`,`IMAGE_URL`,`COLOR_CODE`)
VALUES(Programação,programacao,null,Programe nas principais linguagens e plataformas. Iniciantes são bem vindos nos cursos de lógica e JavaScript.,ACTIVE,1,https://www.alura.com.br/assets/api/formacoes/categorias/512/programacao-transparent.png,#00c86f)
INSERT INTO CATEGORY (`NAME`,`CODE`,`STUDY_GUIDE`,`DESCRIPTION`,`STATUS`,`ORDER`,`IMAGE_URL`,`COLOR_CODE`)
VALUES(DevOps,devops,null,Aprenda Git. Entenda a entrega contínua. Estude Linux. Gerencie servidores na nuvem. Explore o mundo de Internet das coisas e da robótica.,ACTIVE,2,https://www.alura.com.br/assets/api/formacoes/categorias/512/devops-transparent.png,#f16165)
INSERT INTO CATEGORY (`NAME`,`CODE`,`STUDY_GUIDE`,`DESCRIPTION`,`STATUS`,`ORDER`,`IMAGE_URL`,`COLOR_CODE`)
VALUES(Business,business,null,Agilidade. Práticas de gestão. Vendas. Liderança.,DISABLED,0,https://www.alura.com.br/assets/api/formacoes/categorias/512/inovacao-gestao-transparent.png,#ff8c2a)
INSERT INTO SUBCATEGORY (`NAME`,`CODE`,`STUDY_GUIDE`,`DESCRIPTION`,`STATUS`,`ORDER`,`FK_CATEGORY`)
VALUES('Java','java','null','Java é uma grande plataforma presente em todo lugar: de corporações à bancos e governo. Desenvolva aplicações robustas com um back-end e construa APIs.',ACTIVE,1,(SELECT `id` FROM category WHERE `code`='programacao'))
INSERT INTO SUBCATEGORY (`NAME`,`CODE`,`STUDY_GUIDE`,`DESCRIPTION`,`STATUS`,`ORDER`,`FK_CATEGORY`)
VALUES('Java e Persistência','java-e-persistencia','null','',ACTIVE,2,(SELECT `id` FROM category WHERE `code`='programacao'))
INSERT INTO SUBCATEGORY (`NAME`,`CODE`,`STUDY_GUIDE`,`DESCRIPTION`,`STATUS`,`ORDER`,`FK_CATEGORY`)
VALUES('PHP','php','null','PHP é uma das linguagens mais utilizadas.',ACTIVE,3,(SELECT `id` FROM category WHERE `code`='programacao'))
INSERT INTO SUBCATEGORY (`NAME`,`CODE`,`STUDY_GUIDE`,`DESCRIPTION`,`STATUS`,`ORDER`,`FK_CATEGORY`)
VALUES('COBOL','cobol','null','',DISABLED,0,(SELECT `id` FROM category WHERE `code`='programacao'))
INSERT INTO SUBCATEGORY (`NAME`,`CODE`,`STUDY_GUIDE`,`DESCRIPTION`,`STATUS`,`ORDER`,`FK_CATEGORY`)
VALUES('Builds e Controle de versão','builds-e-controle-de-versao','null','As ferramentas mais utilizadas para desenvolvimento: controle de versão com Git e Github além de build da aplicação através de Maven.',ACTIVE,1,(SELECT `id` FROM category WHERE `code`='devops'))

